### ISSUE TITLE
Check Digit 10 Should Be Mapped to 0

### ISSUE THREAD

**Issue by bezborodow** [langerheiko/Calc-ILU-check-digit#1]
According to ***ISO 6346** Freight containers — Coding, identification and marking*, if the check digit is ten (10), then it should be mapped to zero (0.)

Expected:

```
> calcIluCheckDigit('GABU3070070');
0
```

Actual:

```
> calcIluCheckDigit('GABU3070070');
10
```

**Comment by bezborodow** [comment]
> If the final difference is 10, then the check digit becomes 0.

**Comment by bezborodow** [comment]
Fixed by #2.

**Comment by bezborodow** [comment]
I had an afterthought about this. There are actually two use-cases for this function:

 1) Verifying check digits.
 2) Assigning numbers.

When verifying check digits, it is necessary to map 10 to 0.

However, the standard recommends that check digits of 10 should be avoided when assigning numbers to containers. Therefore, those who are using this function to assign numbers may need to know if the check digit is 10 to avoid assigning that number.

If there are users that use this function to assign numbers to containers, than we can add an option to preserve the 10 check digit to facilitate the second use-case.

**Comment by langerheiko** [comment]
👍 
You are free to do so. I will not, as I am currently not working in a warehouse area anymore and not really need this function.
So, if it is something you need or of your interest, then go for it.
